version: 2

updates:
    - package-ecosystem: 'composer'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'thursday'
      versioning-strategy: lockfile-only
      open-pull-requests-limit: 10
      commit-message:
          prefix: 'Composer'
      allow:
          - dependency-type: 'direct'
      groups:
          phpunit:
              patterns:
                  - 'phpunit/phpunit'
                  - 'wp-phpunit/wp-phpunit'
                  - 'yoast/phpunit-polyfills'

    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'thursday'
      versioning-strategy: lockfile-only
      open-pull-requests-limit: 10
      commit-message:
          prefix: 'npm'
      allow:
          - dependency-type: 'direct'
          - dependency-name: '@wordpress/*'
            dependency-type: 'all'
      groups:
          wordpress:
              patterns:
                  - '@wordpress/*'
