name: Feature request
description: Propose an idea for a feature or an enhancement
body:
    - type: textarea
      attributes:
          label: What problem does this address?
          description: Please describe if this feature or enhancement is related to a current problem or pain point. For example, "I'm always frustrated when ..." or "It is currently difficult to ...".
          placeholder: |
              It is currently difficult to ...
      validations:
          required: true

    - type: textarea
      attributes:
          label: What is your proposed solution?
          description: Please outline the feature or enhancement that you want and how it addresses any problem identified above.
      validations:
          required: true

    - type: dropdown
      id: existing
      attributes:
          label: Please confirm that you have searched existing issues in the repo.
          description: You can do this by searching https://github.com/WordPress/wp-feature-notifications/issues.
          multiple: true
          options:
              - 'Yes'
              - 'No'
      validations:
          required: true
