name: JS Continuous Integration

on:
    pull_request:
        branches: [develop, trunk]
    push:
        branches: [feature/mvp]
    workflow_dispatch:

jobs:
    build:
        name: Build plugin
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                node-version: [16.x, 18.x]
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: ./.github/actions/node

            - name: Build package
              shell: bash
              run: npm run build --if-present
