name: Release

on:
    push:
        tags:
            - '*.*.*'

env:
    PLUGIN_SLUG: wp-feature-notifications

jobs:
    release:
        name: Create Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: ./.github/actions/node
              with:
                  node-version: '16'

            - name: Build package
              shell: bash
              run: npm run build --if-present

            - name: Create artifacts
              shell: bash
              run: rsync -rc --exclude-from="${GITHUB_WORKSPACE}/.distignore" "${GITHUB_WORKSPACE}/" "${PLUGIN_SLUG}/" --delete --delete-excluded && zip -r "${GITHUB_WORKSPACE}/${PLUGIN_SLUG}.zip" "${PLUGIN_SLUG}"

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  name: github.ref
                  files: ${{ PLUGIN_SLUG }}.zip
                  fail_on_unmatched_files: true
                  target_commitish: trunk
                  generate_release_notes: true
                  draft: true

    build-docs:
        name: Deploy documentation to GitHub Pages
        runs-on: ubuntu-latest
        needs: release

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: ./.github/actions/node

            - name: Build Storybook
              shell: bash
              run: npm run build:storybook

            - name: Deploy
              uses: peaceiris/actions-gh-pages@64b46b4226a4a12da2239ba3ea5aa73e3163c75b # v3.9.1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
                  force_orphan: true
